### ISSUE TITLE
Add PVP to Versioning

### ISSUE THREAD

**Issue by hasufell** [fosskers/versions#13]
https://github.com/fosskers/versions/blob/298d792652538cf126c90b45bcd2a5679a67dedc/Data/Versions.hs#L92-L96

I noticed PVP is not in Versioning. I guess the main problem is that PVP doesn't safely degrade to SemVer and SemVer doesn't safely degrade to PVP. Is that a semantics of Versioning (in respect to the Ord instance) that is expected?

**Comment by fosskers** [comment]
Oh, looks like you were the one who initial requested the feature over on Gitlab :)

I believe I left `PVP` out of `Versioning` for exactly the reason you state. That, and not changing `Versioning` meant I could release without breaking the existing API. Further, semver in general is language-independent, while PVP is Haskell-specific. I wrote `versions` to use in [Aura](https://github.com/fosskers/aura), where PVP is nowhere to be seen.

**Comment by fosskers** [comment]
Hi there, any thoughts?

**Comment by hasufell** [comment]
I can understand that PVP isn't useful for Aura. However, PVP is in fact older than SemVer. What I could think of is to remove the Ord instance and factor it out into a function such as:

```hs
cmpVer :: MonadThrow m => Versioning -> Versioning -> m Ordering
```

Then... if conversion to or from PVP fails, we can throw. Just throwing out ideas.

**Comment by fosskers** [comment]
If you could elaborate on how you'd like to use the `PVP` type (embedded in `Versioning` or not), perhaps we could find a solution?

**Comment by fosskers** [comment]
Any more thoughts on this, or shall I close?

**Comment by hasufell** [comment]
I don't have a strong opinion, so not sure what to do

**Comment by fosskers** [comment]
I think it's best that we leave `PVP` as its own separate type for the original reason you cited:

> I guess the main problem is that PVP doesn't safely degrade to SemVer and SemVer doesn't safely degrade to PVP.
