### ISSUE TITLE
Empty string "" is a valid version?

### ISSUE THREAD

**Issue by bitc** [fosskers/versions#32]
Hello. It appears that when calling `versioning ""` we get a valid version:

```haskell
(General (Version {_vEpoch = Nothing, _vChunks = [[]], _vRel = []}))
```

Is this intended? I personally think this should be an error, but either way maybe it is worth documenting

Thank you

**Comment by fosskers** [comment]
Thank you for this an your other issue. I'm going to compare this with my [Rust port](https://github.com/fosskers/rs-versions) and make sure they do the same thing. Overall I think you're right - an empty string should be failing there.

**Comment by fosskers** [comment]
Looks like the Rust version does the right thing with whitespace and empty strings. I added some tests to prove it: https://github.com/fosskers/rs-versions/commit/a6e327a3c687dc49208b394b271878537b85884a

Now I'll make sure that this Haskell version behaves the same way.
