### ISSUE TITLE
Parsing version string with trailing whitespace

### ISSUE THREAD

**Issue by bitc** [fosskers/versions#33]
Hello. When parsing a string with trailing whitespace, the trailing whitespace is ignored and the parse succeeds:

```haskell
> versioning "1   \t  \n "

Right (General (Version {_vEpoch = Nothing, _vChunks = [[Digits 1]], _vRel = []}))
```

If there is leading whitespace we get an error:

```haskell
> versioning " 1"
Left (ParseErrorBundle {bundleErrors = TrivialError 1 (Just (Tokens ('1' :| ""))) (fromList [Label ('w' :| "hite space"),EndOfInput]) :| [], bundlePosState = PosState {pstateInput = " 1", pstateOffset = 0, pstateSourcePos = SourcePos {sourceName = "versioning", sourceLine = Pos 1, sourceColumn = Pos 1}, pstateTabWidth = Pos 8, pstateLinePrefix = ""}})
```

I personally think that trailing whitespace should also be an error (I've never seen in the wild a "version" that contains whitespace characters. And this packages rightfully rejects versions with whitespace in the middle of the string, so it should do the same also for whitespace at the end. Also, trailing whitespace breaks the round-trip parse/print property)

Thank you

**Comment by fosskers** [comment]
These fixes will be included in the next release, once I make one more patch.

**Comment by fosskers** [comment]
I made a release.
