### ISSUE TITLE
Generic instances

### ISSUE THREAD

**Issue by taktoa** [fosskers/versions#6]
In my opinion, there are a few typeclasses for which most (serializable, non-abstract) datatypes should have instances. The bare minimum in my view includes `Generic` and `Data`, but `Ord` (for use with `containers`), `Hashable` (for use with `unordered-containers`), and `NFData` (allows `deepseq`) are also often useful. Defining these instances in this library would prevent downstream users from having to add orphan instances (which can be very problematic if the downstream user is itself a library) or newtype wrappers. This problem is exacerbated if the datatype in question is one that is likely to be included as a part of a larger datatype, which seems likely for the types in this library. Since this library doesn't define very many types, the slightly increased compile times shouldn't be a problem.

**Comment by fosskers** [comment]
I think this is a great idea, orphaned instances give me heart palpitations (I write Scala by day, and in Scala  orphans are commonplace). Understandably the `Ord` instances for my types here are very specific, but the rest shouldn't be a problem to add.

**Comment by fosskers** [comment]
Should I bother with `Typeable` and `Data`? I was under the impression that `GHC.Generics` is "just better".

**Comment by taktoa** [comment]
The latest version of GHC automatically derives `Typeable` for all types. There is no detriment to deriving `Data`, so I do it whenever GHC allows me to.

**Comment by fosskers** [comment]
From other sources I'm getting:

> Typeable is automatically derived nowadays, and Data is obsolete

and

> `Data' may become deprecated

Are you personally using it?

**Comment by taktoa** [comment]
Nope, feel free not to derive it in that case.

**Comment by fosskers** [comment]
Uploaded to Hackage as `3.1.1`.
