### ISSUE TITLE
Internal use of `Word` makes valid versions platform-specific

### ISSUE THREAD

**Issue by runeksvendsen** [fosskers/versions#73]
While reading the codebase I found the use of `Word` as the internal representation in almost all datatypes related to version numbers. Furthermore, the parser for e.g. the `PVP` type parses this `Word` directly and wraps in the `PVP` constructor: https://github.com/fosskers/versions/blob/b73ea75156cef409c4512ed074dda82b52c5e46e/Data/Versions.hs#L906-L907

This means that what constitutes a valid PVP version, according to the parser, will differ between 32-bit and 64-bit systems: on the former the maximum version number component will be `32^2-1` while for the latter it will `64^2-1`.

Is this indented behavior?

**Comment by fosskers** [comment]
Good catch. Yes, basically intended with the assumption that:
- no one would be silly enough to have a version number that high, and;
- that most people are running on 64

Not a battle-proof assumption, but changing it would break the API, and you're the first person in 8 years to notice this.

**Comment by runeksvendsen** [comment]
> Not a battle-proof assumption, but changing it would break the API, and you're the first person in 8 years to notice this.

As far as I can see, we can fix this in a backwards compatible manner as follows:

1. Change only the parser to parse a `Word64`
2. When converting this parsed value into a `Word`, check if the parsed value `> (maxBound :: Word)` and if so crash with an informative message

**Comment by fosskers** [comment]
Reasonable!

**Comment by fosskers** [comment]
I did some thinking to make sure we're accounting for everything. I saw the options as:

- Do nothing

**Comment by fosskers** [comment]
@runeksvendsen Do you have a 32-bit system to test #74 ?

**Comment by runeksvendsen** [comment]
> @runeksvendsen Do you have a 32-bit system to test #74 ?

I think it should be possible to build and test inside this 32-bit Docker container if you have an amd64 system (ie. not ARM):

```bash
cd versions/ # cd to repo root
docker run --platform "linux/386" -v $(pwd):/src -it hasufell/i386-alpine-haskell:3.16 /bin/bash -c "cd /src; cabal update; cabal test" 
```

**Comment by fosskers** [comment]
Alright, seems to work. Here's what we see on a 32-bit image:
```
18446744073709551610.0.0:                        FAIL
          test/Test.hs:243:
          Semantic Version:1:21:
            |
          1 | 18446744073709551610.0.0
            |                     ^
          Value (18446744073709551610) larger than Word size: 4294967295
```
