### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by bergmark** [fosskers/versions#9]
```
    SemVer - Arbitrary:                          FAIL
      *** Failed! Falsifiable (after 4 tests):
      SemVer {_svMajor = 4, _svMinor = 2, _svPatch = 3, _svPreRel = [[Digits 2,Digits 4,Str "h"],[Digits 0,Digits 2],[Str "gaw"
,Str "tz"]], _svMeta = [[Digits 0],[Str "hnj"],[]]}
      Use --quickcheck-replay=501870 to reproduce.
```

versions was disabled for bounds reasons but now this popped up, please send a PR to re-enable it if it gets fixed or let us know if we should just ignore the test failure.

**Comment by fosskers** [comment]
Thanks! This might just be a problem with the Arbitrary instance for `SemVer`.

**Comment by fosskers** [comment]
https://github.com/fpco/stackage/pull/3051
